# Generated by Django 3.1.1 on 2020-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_api', '0002_auto_20200927_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
