# Generated by Django 3.1.1 on 2020-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_api', '0003_auto_20200927_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
